source 'http://rubygems.org'

# gem 'sinatra', git: "git@github.com:sinatra/sinatra.git"
gem 'sinatra'
gem "sinatra-activerecord"
gem "sqlite3"
gem "rake"
gem 'rack', '>= 1.1', '< 1.6'
gem 'sinatra-asset-pipeline'
gem 'racksh'
gem "sprockets"
gem 'httparty'
gem 'faraday'
gem 'sass', '~> 3.1'
gem 'coffee-script-source' ,'>= 0'
gem 'execjs' ,'>= 0'
gem 'multi_json', '~> 1.0'
gem 'foundation'
gem 'compass'